name: Release Android APK

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build-release:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept Android licenses
        run: yes | sdkmanager --licenses

      - name: Install Android platforms and tools
        run: |
          sdkmanager --install "platform-tools" "platforms;android-36" "build-tools;35.0.0"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Flutter pub get
        run: flutter pub get

      - name: Build release APK (arm64)
        run: flutter build apk --release --target-platform=android-arm64

      - name: Rename APK for release
        run: |
          cp build/app/outputs/flutter-apk/app-release.apk binaryRunnerAndroid.apk

      - name: Upload APK to Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            binaryRunnerAndroid.apk
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
